### ISSUE TITLE
Not able to specify dynamic template ID in html attribute of tippy options

### ISSUE THREAD

**Issue by gomteshhatgine** [Teebo/ng-tippy#3]
Hi,
   How can I specify dynamic custom template ID in html attribute value of tippy options

`
<ng-template let-customer ngFor [ngForOf]="customerList" let-i="index">`

	`<div  id="'my-template' + i" style="display: none;">		

		<div *ngFor="let message of customer.ErrMessages">{{message}}<br/></div>	
		
	</div>

	<span class="alert-icon"  appTooltip [options]="{html: '#'my-template' + i'}"></span>

	<label> {{customer.name}} </label>`

`</ng-template>`

**Comment by Teebo** [comment]
Hi, 

Do you want to attach a tooltip to every ErrorMessage?

**Comment by Teebo** [comment]
Move the the customer name and error span to a separate `ng-template` like so

```
<ng-template let-customer ngFor [ngForOf]="customerList" let-i="index">
<div [attr.id]="'my-template-'+i" style="display:none;">		
	<div *ngFor="let message of customer.ErrMessages">{{message}}</div>	
  <br/>
</div>
</ng-template>

<ng-template let-customer ngFor [ngForOf]="customerList" let-i="index">
  <span class="alert-icon" appTippy [tippyOptions]="{html:'#my-template-' + i}"><label>{{customer.name}} - </label>Error messages
  </span><br/>
</ng-template>
```
This will give a chance for the first template to render and then the tippy will have a reference to an existing `ErrMessage` div, this is not a viable solution but should do for now. See how `[attr.id]="'my-template-'+i"` is used to give the error `div` the `id` attribute. I will see how to support such use cases, hope this helps.

**Comment by gomteshhatgine** [comment]
Thanks it worked

**Comment by Teebo** [comment]
@gomteshhatgine I'm glad it helped, just one more thing, please update to the latest ng-tippy version, the previous versions had bugs.
